#!/usr/bin/env bash

PTP_STARTED_CHRONYD_PID=""
PTP_CHRONY_CONFIG=""
PTP_CHRONY_SOCKET=""
PTP_CHRONY_CMD_PORT=32322

ptp_ntp_server_words() {
    local servers=${1//,/ } item
    local -a items=()
    read -r -a items <<<"$servers"
    for item in "${items[@]}"; do printf '%s\n' "$item"; done
}

ptp_validate_ntp_servers() {
    local servers=$1 server count=0
    [[ -n ${servers//[[:space:],]/} ]] || ptp_die "NTP_SERVERS must contain at least one hostname or IP when NTP is enabled" || return
    while IFS= read -r server; do
        [[ -n $server ]] || continue
        ((count += 1))
        [[ $server =~ ^[A-Za-z0-9][A-Za-z0-9._:-]*$ ]] || {
            ptp_die "Invalid NTP server '$server'; use hostnames or IP addresses separated by spaces or commas" || return
        }
        [[ $server != *..* && $server != *:::* ]] || {
            ptp_die "Invalid NTP server '$server'" || return
        }
    done < <(ptp_ntp_server_words "$servers")
    (( count > 0 )) || ptp_die "No valid NTP server was provided"
}

ptp_generate_chrony_config() {
    local output=$1 server
    [[ ${PTP_CHRONY_MODE:-OFF} != OFF ]] || ptp_die "Internal error: chrony config requested for OFF policy" || return
    ptp_validate_ntp_servers "$NTP_SERVERS" || return
    PTP_CHRONY_CONFIG=$output
    # The private instance uses loopback monitoring on a non-default command
    # port. This keeps validation isolated, and lets an unprivileged
    # `ptpctl status` issue only the read-only monitoring commands chronyd
    # permits over the network interface.
    PTP_CHRONY_SOCKET="127.0.0.1"
    {
        echo "# Private runtime configuration generated by ptpctl."
        echo "# It never reads or overwrites /etc/chrony.conf."
        while IFS= read -r server; do
            [[ -n $server ]] && printf 'server %s iburst\n' "$server"
        done < <(ptp_ntp_server_words "$NTP_SERVERS")
        echo "pidfile $PTP_RUN_DIR/chronyd.pid"
        echo "bindcmdaddress $PTP_CHRONY_SOCKET"
        echo "cmdport $PTP_CHRONY_CMD_PORT"
        echo "port 0"
        if [[ $PTP_CHRONY_MODE == DISCIPLINE ]]; then
            echo "makestep 1.0 3"
        else
            echo "# CLOCK_REALTIME protection is enforced by the chronyd -x command-line option."
        fi
    } > "$output"
    chmod 0600 "$output"
}

ptp_validate_ntp_names() {
    local server failed=0
    while IFS= read -r server; do
        [[ -n $server ]] || continue
        if ! getent ahosts "$server" >/dev/null 2>&1; then
            ptp_error "NTP server cannot be resolved or found locally: $server"
            failed=1
        fi
    done < <(ptp_ntp_server_words "$NTP_SERVERS")
    (( failed == 0 ))
}

ptp_validate_chrony_config() {
    local config=$1 log=$2 output
    output="$(chronyd -p -f "$config" 2>&1)" || {
        { echo "=== chronyd configuration validation ==="; printf '%s\n' "$output"; } >> "$log"
        ptp_error "Private chrony configuration is invalid. See $log"
        return 1
    }
    { echo "=== chronyd configuration validation ==="; printf '%s\n' "$output"; } >> "$log"
}

ptp_probe_ntp_sources() {
    local config=$1 log=$2 output
    output="$(chronyd -Q -t "$NTP_PROBE_TIMEOUT_SECONDS" -f "$config" 2>&1)" || {
        { echo "=== NTP reachability probe ==="; printf '%s\n' "$output"; } >> "$log"
        ptp_error "No configured NTP source produced a usable probe response. See $log"
        return 1
    }
    { echo "=== NTP reachability probe ==="; printf '%s\n' "$output"; } >> "$log"
    ptp_ok "Configured NTP source reachability probe succeeded"
}

ptp_chronyc_query() {
    local socket=$1 log=$2 command=$3 output
    output="$(chronyc -h "$socket" -p "$PTP_CHRONY_CMD_PORT" -n "$command" 2>&1)" || {
        if [[ -w $log || ( ! -e $log && -w $(dirname "$log") ) ]]; then
            { echo "=== $(date --iso-8601=seconds) chronyc $command ==="; printf '%s\n' "$output"; } >> "$log"
        fi
        return 1
    }
    if [[ -w $log || ( ! -e $log && -w $(dirname "$log") ) ]]; then
        { echo "=== $(date --iso-8601=seconds) chronyc $command ==="; printf '%s\n' "$output"; } >> "$log"
    fi
    printf '%s\n' "$output"
}

ptp_ntp_has_selected_source() {
    grep -Eq '^[#^=][*+]' <<<"$1"
}

ptp_wait_for_ntp_source() {
    local socket=$1 timeout_seconds=$2 status_log=$3 start now sources tracking
    start=$(date +%s)
    while true; do
        if [[ -n ${PTP_STARTED_CHRONYD_PID:-} ]] && ! kill -0 "$PTP_STARTED_CHRONYD_PID" 2>/dev/null; then
            ptp_error "private chronyd exited while waiting for an NTP source"
            return 1
        fi
        sources="$(ptp_chronyc_query "$socket" "$status_log" sources 2>/dev/null || true)"
        tracking="$(ptp_chronyc_query "$socket" "$status_log" tracking 2>/dev/null || true)"
        if ptp_ntp_has_selected_source "$sources" && grep -Eq '^Leap status[[:space:]]*:[[:space:]]*Normal' <<<"$tracking"; then
            if [[ $PTP_CHRONY_MODE != DISCIPLINE ]] ||
                ptp_chronyc_query "$socket" "$status_log" 'waitsync 1' >/dev/null 2>&1; then
                return 0
            fi
        fi
        now=$(date +%s)
        (( now - start < timeout_seconds )) || {
            ptp_error "Timed out waiting for a usable synchronized NTP source"
            return 1
        }
        sleep 2
    done
}

ptp_start_private_chronyd() {
    local config=$1 log=$2 status_log=$3
    # -d keeps the daemon in the foreground and sends its diagnostic stream to
    # the ptpctl-owned chronyd log instead of the system chrony/syslog path.
    local -a args=(-d -f "$config")
    [[ $PTP_CHRONY_MODE == MONITOR_ONLY ]] && args=(-d -x -f "$config")
    PTP_STARTED_CHRONYD_PID="$(ptp_start_background chronyd "$log" chronyd "${args[@]}")" || return
    ptp_wait_for_ntp_source "$PTP_CHRONY_SOCKET" "$NTP_SYNC_TIMEOUT_SECONDS" "$status_log" || return
    if [[ $PTP_CHRONY_MODE == MONITOR_ONLY ]]; then
        ptp_ok "NTP monitor is usable; chronyd -x cannot adjust CLOCK_REALTIME"
    else
        ptp_ok "NTP client has a usable synchronized source and owns CLOCK_REALTIME"
    fi
}

ptp_ntp_status_fields() {
    local socket=$1 log=$2 sources tracking reachability stratum offset reference frequency
    sources="$(ptp_chronyc_query "$socket" "$log" sources 2>/dev/null || true)"
    tracking="$(ptp_chronyc_query "$socket" "$log" tracking 2>/dev/null || true)"
    if ptp_ntp_has_selected_source "$sources"; then reachability=OK; else reachability=UNUSABLE; fi
    stratum="$(awk -F':[[:space:]]*' '/^Stratum/ {print $2; exit}' <<<"$tracking")"
    offset="$(awk -F':[[:space:]]*' '/^(System time|Last offset)/ {print $2; exit}' <<<"$tracking")"
    reference="$(awk -F':[[:space:]]*' '/^Reference ID/ {print $2; exit}' <<<"$tracking")"
    frequency="$(awk -F':[[:space:]]*' '/^Frequency/ {print $2; exit}' <<<"$tracking")"
    printf '%-20s %s\n' "Reachability:" "$reachability"
    printf '%-20s %s\n' "Stratum:" "${stratum:-unknown}"
    printf '%-20s %s\n' "Offset:" "${offset:-unknown}"
    printf '%-20s %s\n' "Reference ID:" "${reference:-unknown}"
    printf '%-20s %s\n' "Frequency estimate:" "${frequency:-unknown}"
}
