#!/usr/bin/env bash

PTP_STARTED_PTP4L_PID=""
PTP_STARTED_PHC2SYS_PID=""
PTP_CURRENT_STATE_FILE="$PTP_RUN_DIR/state.env"
PTP_RUNTIME_CONFIG=""
PTP_SETUP_TRANSACTION_ACTIVE=0

ptp_mode_parse() {
    local mode=$1
    case "$mode" in
        I350-master) PTP_MODE=$mode; PTP_FAMILY=I350; PTP_ROLE=master ;;
        I350-slave)  PTP_MODE=$mode; PTP_FAMILY=I350; PTP_ROLE=slave ;;
        X710-master) PTP_MODE=$mode; PTP_FAMILY=X710; PTP_ROLE=master ;;
        X710-slave)  PTP_MODE=$mode; PTP_FAMILY=X710; PTP_ROLE=slave ;;
        *) ptp_die "Unsupported mode '$mode'. Use I350-master, I350-slave, X710-master, or X710-slave." || return ;;
    esac
}

ptp_selected_unpack() {
    IFS=$'\t' read -r PTP_IFACE PTP_FAMILY_SELECTED PTP_PCI PTP_MODEL PTP_DRIVER \
        PTP_FIRMWARE PTP_LINK PTP_MAC PTP_PHC PTP_PHC_SYSFS PTP_HW_TX PTP_HW_RX \
        PTP_HW_RAW PTP_VALID PTP_REASON <<<"$PTP_SELECTED_CANDIDATE"
}

ptp_print_selection_summary() {
    echo "PTP Setup Summary"
    echo
    printf '%-18s %s\n' "Mode:" "$PTP_MODE"
    printf '%-18s %s\n' "NIC:" "Intel $PTP_FAMILY_SELECTED"
    printf '%-18s %s\n' "Interface:" "$PTP_IFACE"
    printf '%-18s %s\n' "PCI:" "$PTP_PCI"
    printf '%-18s %s\n' "Driver:" "$PTP_DRIVER"
    printf '%-18s %s\n' "Firmware:" "$PTP_FIRMWARE"
    printf '%-18s %s\n' "Link:" "$([[ $PTP_LINK == 1 ]] && echo UP || echo DOWN)"
    printf '%-18s %s\n' "MAC:" "$PTP_MAC"
    printf '%-18s %s\n' "HW TX timestamp:" "${PTP_HW_TX^^}"
    printf '%-18s %s\n' "HW RX timestamp:" "${PTP_HW_RX^^}"
    printf '%-18s %s\n' "Hardware raw clock:" "${PTP_HW_RAW^^}"
    printf '%-18s %s\n' "PHC:" "$PTP_PHC"
    printf '%-18s %s\n' "PHC shared:" "$(ptp_candidate_phc_sharing "$PTP_SELECTED_CANDIDATE")"
    printf '%-18s %s\n' "PHC sysfs:" "$PTP_PHC_SYSFS"
    echo
    printf '%-18s %s\n' "PTP domain:" "$PTP_DOMAIN"
    printf '%-18s %s\n' "Transport:" "$PTP_TRANSPORT"
    printf '%-18s %s\n' "Delay mechanism:" "$PTP_DELAY_MECHANISM"
    printf '%-18s %s\n' "PTP profile:" "$PTP_PROFILE"
    printf '%-18s %s\n' "transportSpecific:" "$TRANSPORT_SPECIFIC"
    if [[ $PTP_ROLE == slave ]]; then
        printf '%-18s %s\n' "GM discovery:" "$GRANDMASTER_DISCOVERY"
    else
        printf '%-18s %s\n' "Master policy:" "$MASTER_TIME_POLICY"
        printf '%-18s %s\n' "TAI-UTC offset:" "$MASTER_UTC_OFFSET"
        if ! ptp_is_todo "${MASTER_UTC_OFFSET_AUTHORITY:-}"; then
            printf '%-18s %s\n' "UTC authority:" "$MASTER_UTC_OFFSET_AUTHORITY"
        fi
        printf '%-18s %s\n' "System time:" "${PTP_MASTER_SOURCE_STATUS:-unknown}"
    fi
    echo
    printf '%-18s %s\n' "Clock conflicts:" "${PTP_CLOCK_CONFLICTS:-none}"
}

ptp_generate_runtime_config() {
    local role=$1 iface=$2 output=$3 uds=$4 base
    base="$PTPCTL_ROOT/configs/ptp4l-$role.conf"
    [[ -r $base ]] || ptp_die "Missing role template: $base" || return
    {
        cat "$base"
        echo
        echo "# Generated by ptpctl for $PTP_MODE at $(date --iso-8601=seconds)"
        echo "domainNumber            $PTP_DOMAIN"
        echo "network_transport       $PTP_TRANSPORT"
        echo "delay_mechanism         $PTP_DELAY_MECHANISM"
        echo "transportSpecific       $TRANSPORT_SPECIFIC"
        echo "uds_address             $uds"
        echo "uds_ro_address          ${uds}ro"
        [[ $role == master ]] && echo "utc_offset              $MASTER_UTC_OFFSET"
        if [[ $PROFILE_EXTRA_CONFIG != NONE ]]; then
            echo
            echo "# Reviewed profile additions: $PROFILE_EXTRA_CONFIG"
            cat "$PROFILE_EXTRA_CONFIG"
        fi
        echo
        echo "[$iface]"
    } > "$output"
    chmod 0600 "$output"
}

ptp_record_pre_state() {
    local target=$1
    {
        echo "timestamp=$(date --iso-8601=seconds)"
        echo "mode=$PTP_MODE"
        echo "interface=$PTP_IFACE"
        echo "pci=$PTP_PCI"
        echo "driver=$PTP_DRIVER"
        echo "phc=$PTP_PHC"
        echo
        echo "=== clock services ==="
        ptp_clock_service_report
        echo
        echo "=== timedatectl ==="
        timedatectl 2>&1 || true
        echo
        echo "=== link ==="
        ip -details link show dev "$PTP_IFACE" 2>&1 || true
        echo
        echo "=== processes ==="
        ptp_process_lines ptp4l
        ptp_process_lines phc2sys
    } > "$target"
}

ptp_check_existing_ptp_processes() {
    local found=0
    PTP_CLOCK_CONFLICTS=none
    if pgrep -x ptp4l >/dev/null 2>&1; then
        ptp_error "An existing ptp4l process would conflict:"
        ptp_process_lines ptp4l | sed 's/^/  /' >&2
        found=1
    fi
    if pgrep -x phc2sys >/dev/null 2>&1; then
        ptp_error "An existing phc2sys process would conflict:"
        ptp_process_lines phc2sys | sed 's/^/  /' >&2
        found=1
    fi
    (( found == 0 )) || {
        PTP_CLOCK_CONFLICTS="existing ptp4l/phc2sys"
        ptp_error "Stop the existing deployment deliberately before running ptpctl setup."
        return 1
    }
}

ptp_check_role_clock_policy() {
    local role=$1
    echo "Checking clock services..."
    ptp_clock_service_report
    if [[ ${PTPCTL_TEST_MODE:-0} == 1 && ${PTPCTL_TEST_CLOCK_CONFLICT:-0} == 1 && $role == slave ]]; then
        PTP_CLOCK_CONFLICTS="active system clock discipliner"
        ptp_error "Slave mode will use phc2sys to discipline CLOCK_REALTIME, but another discipliner is active."
        return 1
    fi
    if [[ ${PTPCTL_TEST_MODE:-0} == 1 && ${PTPCTL_TEST_CLOCK_POLICY_LIVE:-0} != 1 ]]; then
        PTP_MASTER_SOURCE_STATUS="mock-validated"
        ptp_ok "Mock clock policy accepted for dry-run testing"
        return 0
    fi
    if [[ $role == slave ]]; then
        if ptp_other_system_discipliner; then
            PTP_CLOCK_CONFLICTS="active system clock discipliner"
            ptp_error "Slave mode will use phc2sys to discipline CLOCK_REALTIME, but another discipliner is active."
            ptp_error "Stop the active service temporarily, for example: sudo systemctl stop chronyd"
            ptp_error "Do not disable it permanently until the final clock architecture is approved."
            return 1
        fi
        ptp_ok "No competing CLOCK_REALTIME discipliner detected"
    else
        if ptp_system_clock_synchronized; then
            PTP_MASTER_SOURCE_STATUS=synchronized
            ptp_ok "CLOCK_REALTIME reports an upstream synchronization source"
        elif [[ $MASTER_TIME_POLICY == ALLOW_LAB_FREERUN ]]; then
            PTP_MASTER_SOURCE_STATUS=free-running-lab
            ptp_warn "LAB MASTER ONLY: CLOCK_REALTIME is not proven synchronized."
            ptp_warn "This server will act as a PTP protocol master, but its time is not traceable or guaranteed accurate."
        else
            ptp_error "CLOCK_REALTIME is not proven synchronized and MASTER_TIME_POLICY=REQUIRE_SYNCED_SYSTEM."
            ptp_error "Configure/verify chrony or another upstream source, then rerun doctor and setup."
            return 1
        fi
    fi
}

ptp_start_background() {
    local name=$1 log=$2
    shift 2
    setsid "$@" >> "$log" 2>&1 &
    local pid=$!
    sleep 1
    if ! kill -0 "$pid" 2>/dev/null; then
        ptp_error "$name exited during startup. Recent log:"
        tail -n 40 "$log" >&2 || true
        return 1
    fi
    printf '%s\n' "$pid"
}

ptp_pmc_query() {
    local uds=$1 log=$2 command=$3 output
    output="$(pmc -u -b 0 -d "$PTP_DOMAIN" -s "$uds" "$command" 2>&1)" || {
        printf '%s\n' "$output" >> "$log"
        return 1
    }
    { echo "=== $(date --iso-8601=seconds) $command ==="; printf '%s\n' "$output"; } >> "$log"
    printf '%s\n' "$output"
}

ptp_wait_for_port_state() {
    local desired=$1 uds=$2 timeout_seconds=$3 pmc_log=$4 start now output state
    start=$(date +%s)
    while true; do
        if [[ -n ${PTP_STARTED_PTP4L_PID:-} ]] && ! kill -0 "$PTP_STARTED_PTP4L_PID" 2>/dev/null; then
            ptp_error "ptp4l exited while waiting for state $desired"
            return 1
        fi
        output="$(ptp_pmc_query "$uds" "$pmc_log" 'GET PORT_DATA_SET' 2>/dev/null || true)"
        state="$(awk '/portState/ {print $2; exit}' <<<"$output")"
        [[ $state == "$desired" ]] && { echo "$state"; return 0; }
        now=$(date +%s)
        (( now - start < timeout_seconds )) || {
            ptp_error "Timed out waiting for ptp4l state $desired (last state: ${state:-unknown})."
            return 1
        }
        sleep 2
    done
}

ptp_validate_slave_management() {
    local uds=$1 pmc_log=$2 properties status timescale offset_valid offset
    properties="$(ptp_pmc_query "$uds" "$pmc_log" 'GET TIME_PROPERTIES_DATA_SET')" || return
    timescale="$(awk '$1 == "ptpTimescale" {print $2; exit}' <<<"$properties")"
    offset_valid="$(awk '$1 == "currentUtcOffsetValid" {print $2; exit}' <<<"$properties")"
    offset="$(awk '$1 == "currentUtcOffset" {print $2; exit}' <<<"$properties")"
    [[ $timescale == 1 ]] || {
        ptp_die "Grandmaster does not advertise PTP timescale; refusing phc2sys" || return
    }
    [[ $offset_valid == 1 ]] || {
        ptp_die "Grandmaster currentUtcOffset is not valid; refusing a tens-of-seconds clock error" || return
    }
    [[ $offset =~ ^-?[0-9]+$ ]] || {
        ptp_die "Grandmaster currentUtcOffset is not numeric" || return
    }
    status="$(ptp_pmc_query "$uds" "$pmc_log" 'GET TIME_STATUS_NP' 2>/dev/null || true)"
    [[ -n $status ]] || ptp_warn "TIME_STATUS_NP was unavailable; PORT_DATA_SET and UTC properties remain valid"
}

ptp_validate_master_utc() {
    local uds=$1 pmc_log=$2 properties advertised
    properties="$(ptp_pmc_query "$uds" "$pmc_log" 'GET TIME_PROPERTIES_DATA_SET')" || return
    advertised="$(awk '/currentUtcOffset[[:space:]]/ {print $2; exit}' <<<"$properties")"
    [[ $advertised == "$MASTER_UTC_OFFSET" ]] || {
        ptp_die "ptp4l advertises currentUtcOffset=${advertised:-unknown}, expected confirmed MASTER_UTC_OFFSET=$MASTER_UTC_OFFSET" || return
    }
    ptp_ok "Master TAI-UTC offset confirmed through pmc: $advertised seconds"
}

ptp_verify_phc2sys() {
    local pid=$1 log=$2 seconds=$3
    sleep "$seconds"
    kill -0 "$pid" 2>/dev/null || {
        ptp_error "phc2sys exited. Recent log:"
        tail -n 50 "$log" >&2 || true
        return 1
    }
    grep -Eq '(^|[[:space:]])offset[[:space:]]+-?[0-9]+' "$log" || {
        ptp_error "phc2sys is running but produced no verified clock-update sample within ${seconds}s."
        tail -n 30 "$log" >&2 || true
        return 1
    }
}

ptp_stop_pid() {
    local pid=$1 expected=$2
    [[ $pid =~ ^[0-9]+$ && -d /proc/$pid ]] || return 0
    [[ $(cat "/proc/$pid/comm" 2>/dev/null || true) == "$expected" ]] || {
        ptp_warn "PID $pid is no longer $expected; not signaling it"
        return 0
    }
    kill -TERM "$pid" 2>/dev/null || true
    local i
    for i in {1..30}; do kill -0 "$pid" 2>/dev/null || return 0; sleep 0.1; done
    kill -KILL "$pid" 2>/dev/null || true
}

ptp_rollback_started() {
    ptp_warn "Setup failed; stopping only processes started by this ptpctl transaction."
    [[ -n $PTP_STARTED_PHC2SYS_PID ]] && ptp_stop_pid "$PTP_STARTED_PHC2SYS_PID" phc2sys
    [[ -n $PTP_STARTED_PTP4L_PID ]] && ptp_stop_pid "$PTP_STARTED_PTP4L_PID" ptp4l
    rm -f "$PTP_CURRENT_STATE_FILE" "$PTP_RUN_DIR/ptp4l.sock" "$PTP_RUN_DIR/ptp4l.sockro"
    [[ -n $PTP_RUNTIME_CONFIG ]] && rm -f "$PTP_RUNTIME_CONFIG"
    ptp_info "No network configuration, driver binding, service enablement, or boot setting was changed."
}

ptp_setup_signal_rollback() {
    local signal_name=$1
    if [[ $PTP_SETUP_TRANSACTION_ACTIVE == 1 ]]; then
        ptp_error "Setup interrupted by $signal_name"
        ptp_rollback_started
    fi
    exit 130
}

ptp_write_success_state() {
    local config=$1 uds=$2 ptp4l_log=$3 phc2sys_log=$4 pmc_log=$5 setup_log=$6
    ptp_atomic_write_state "$PTP_CURRENT_STATE_FILE" <<EOF
MODE=$PTP_MODE
ROLE=$PTP_ROLE
FAMILY=$PTP_FAMILY_SELECTED
INTERFACE=$PTP_IFACE
PCI=$PTP_PCI
DRIVER=$PTP_DRIVER
PHC=$PTP_PHC
PTP4L_PID=$PTP_STARTED_PTP4L_PID
PHC2SYS_PID=$PTP_STARTED_PHC2SYS_PID
RUNTIME_CONFIG=$config
UDS=$uds
PTP4L_LOG=$ptp4l_log
PHC2SYS_LOG=$phc2sys_log
PMC_LOG=$pmc_log
SETUP_LOG=$setup_log
STARTED_AT=$(date --iso-8601=seconds)
MASTER_SOURCE_STATUS=${PTP_MASTER_SOURCE_STATUS:-external-grandmaster}
EOF
}
