#!/usr/bin/env bash

PTP_STARTED_PTP4L_PID=""
PTP_STARTED_PHC2SYS_PID=""
PTP_STARTED_CHRONYD_PID="${PTP_STARTED_CHRONYD_PID:-}"
PTP_CURRENT_STATE_FILE="$PTP_RUN_DIR/state.env"
PTP_RUNTIME_CONFIG=""
PTP_SETUP_TRANSACTION_ACTIVE=0
PTP_STOPPED_SERVICES=""
PTP_CONFLICTING_SERVICES=""

ptp_mode_parse() {
    local mode=$1
    case "$mode" in
        I350-master) PTP_MODE=$mode; PTP_FAMILY=I350; PTP_ROLE=master ;;
        I350-slave)  PTP_MODE=$mode; PTP_FAMILY=I350; PTP_ROLE=slave ;;
        X710-master) PTP_MODE=$mode; PTP_FAMILY=X710; PTP_ROLE=master ;;
        X710-slave)  PTP_MODE=$mode; PTP_FAMILY=X710; PTP_ROLE=slave ;;
        *) ptp_die "Unsupported mode '$mode'. Use I350-master, I350-slave, X710-master, or X710-slave." || return ;;
    esac
}

ptp_selected_unpack() {
    IFS=$'\t' read -r PTP_IFACE PTP_FAMILY_SELECTED PTP_PCI PTP_MODEL PTP_DRIVER \
        PTP_FIRMWARE PTP_LINK PTP_MAC PTP_PHC PTP_PHC_SYSFS PTP_HW_TX PTP_HW_RX \
        PTP_HW_RAW PTP_VALID PTP_REASON <<<"$PTP_SELECTED_CANDIDATE"
}

ptp_print_selection_summary() {
    echo "Configuration Summary"
    echo
    printf '%-18s %s\n' "Mode:" "$PTP_MODE"
    printf '%-18s %s\n' "NIC:" "Intel $PTP_FAMILY_SELECTED"
    printf '%-18s %s\n' "Interface:" "$PTP_IFACE"
    printf '%-18s %s\n' "PCI:" "$PTP_PCI"
    printf '%-18s %s\n' "Driver:" "$PTP_DRIVER"
    printf '%-18s %s\n' "Firmware:" "$PTP_FIRMWARE"
    printf '%-18s %s\n' "Link:" "$([[ $PTP_LINK == 1 ]] && echo UP || echo DOWN)"
    printf '%-18s %s\n' "MAC:" "$PTP_MAC"
    printf '%-18s %s\n' "HW TX timestamp:" "${PTP_HW_TX^^}"
    printf '%-18s %s\n' "HW RX timestamp:" "${PTP_HW_RX^^}"
    printf '%-18s %s\n' "Hardware raw clock:" "${PTP_HW_RAW^^}"
    printf '%-18s %s\n' "PHC:" "$PTP_PHC"
    printf '%-18s %s\n' "PHC shared:" "$(ptp_candidate_phc_sharing "$PTP_SELECTED_CANDIDATE")"
    printf '%-18s %s\n' "PHC sysfs:" "$PTP_PHC_SYSFS"
    echo
    printf '%-18s %s\n' "PTP domain:" "$PTP_DOMAIN"
    printf '%-18s %s\n' "Transport:" "$PTP_TRANSPORT"
    printf '%-18s %s\n' "Delay mechanism:" "$PTP_DELAY_MECHANISM"
    printf '%-18s %s\n' "PTP profile:" "$PTP_PROFILE"
    printf '%-18s %s\n' "transportSpecific:" "$TRANSPORT_SPECIFIC"
    if [[ $PTP_ROLE == slave ]]; then
        printf '%-18s %s\n' "GM discovery:" "$GRANDMASTER_DISCOVERY"
        printf '%-18s %s\n' "PTP adjusts system:" "$PTP_SLAVE_SYSTEM_CLOCK"
    else
        printf '%-18s %s\n' "Master policy:" "$MASTER_TIME_POLICY"
        printf '%-18s %s\n' "TAI-UTC offset:" "$MASTER_UTC_OFFSET"
        if ! ptp_is_todo "${MASTER_UTC_OFFSET_AUTHORITY:-}"; then
            printf '%-18s %s\n' "UTC authority:" "$MASTER_UTC_OFFSET_AUTHORITY"
        fi
        printf '%-18s %s\n' "System time:" "${PTP_MASTER_SOURCE_STATUS:-unknown}"
    fi
    echo
    printf '%-18s %s\n' "NTP:" "$([[ $NTP_ENABLED == YES ]] && echo ENABLED || echo DISABLED)"
    [[ $NTP_ENABLED == YES ]] && printf '%-18s %s\n' "NTP servers:" "$NTP_SERVERS"
    printf '%-18s %s\n' "NTP mode:" "$(ptp_ntp_mode_display)"
    echo
    printf '%-18s %s\n' "CLOCK_REALTIME:" "$(ptp_clock_owner_display)"
    printf '%-18s %s\n' "NIC PHC:" "$PTP_PHC_OWNER"
    printf '%-18s %s\n' "Architecture:" "$PTP_ARCHITECTURE"
    printf '%-18s %s\n' "Clock conflicts:" "${PTP_CLOCK_CONFLICTS:-NONE}"
}

ptp_generate_runtime_config() {
    local role=$1 iface=$2 output=$3 uds=$4 base
    base="$PTPCTL_ROOT/configs/ptp4l-$role.conf"
    [[ -r $base ]] || ptp_die "Missing role template: $base" || return
    {
        cat "$base"
        echo
        echo "# Generated by ptpctl for $PTP_MODE at $(date --iso-8601=seconds)"
        echo "domainNumber            $PTP_DOMAIN"
        echo "network_transport       $PTP_TRANSPORT"
        echo "delay_mechanism         $PTP_DELAY_MECHANISM"
        echo "transportSpecific       $TRANSPORT_SPECIFIC"
        echo "uds_address             $uds"
        echo "uds_ro_address          ${uds}ro"
        [[ $role == master ]] && echo "utc_offset              $MASTER_UTC_OFFSET"
        if [[ $PROFILE_EXTRA_CONFIG != NONE ]]; then
            echo
            echo "# Reviewed profile additions: $PROFILE_EXTRA_CONFIG"
            cat "$PROFILE_EXTRA_CONFIG"
        fi
        echo
        echo "[$iface]"
    } > "$output"
    chmod 0600 "$output"
}

ptp_record_pre_state() {
    local target=$1
    {
        echo "timestamp=$(date --iso-8601=seconds)"
        echo "mode=$PTP_MODE"
        echo "interface=$PTP_IFACE"
        echo "pci=$PTP_PCI"
        echo "driver=$PTP_DRIVER"
        echo "phc=$PTP_PHC"
        echo
        echo "=== clock services ==="
        ptp_clock_service_report
        echo
        echo "=== timedatectl ==="
        timedatectl 2>&1 || true
        echo
        echo "=== link ==="
        ip -details link show dev "$PTP_IFACE" 2>&1 || true
        echo
        echo "=== processes ==="
        ptp_process_lines chronyd
        ptp_process_lines ntpd
        ptp_process_lines systemd-timesyncd
        ptp_process_lines ptp4l
        ptp_process_lines phc2sys
    } > "$target"
}

ptp_check_existing_ptp_processes() {
    local found=0
    PTP_CLOCK_CONFLICTS=none
    if pgrep -x ptp4l >/dev/null 2>&1; then
        ptp_error "An existing ptp4l process would conflict:"
        ptp_process_lines ptp4l | sed 's/^/  /' >&2
        found=1
    fi
    if pgrep -x phc2sys >/dev/null 2>&1; then
        ptp_error "An existing phc2sys process would conflict:"
        ptp_process_lines phc2sys | sed 's/^/  /' >&2
        found=1
    fi
    (( found == 0 )) || {
        PTP_CLOCK_CONFLICTS="existing ptp4l/phc2sys"
        ptp_error "Stop the existing deployment deliberately before running ptpctl setup."
        return 1
    }
}

ptp_plan_clock_service_conflicts() {
    local service
    local -a active=() process_families=()
    PTP_CONFLICTING_SERVICES=""
    PTP_CLOCK_CONFLICTS=NONE
    mapfile -t active < <(ptp_active_clock_service_units)

    # A ptpctl-owned private discipline instance or phc2sys system target needs
    # exclusive CLOCK_REALTIME ownership. Monitor-only -x also requires existing
    # normal time services to stop because PTP is the selected owner.
    if [[ $PTP_CLOCK_OWNER == PHC2SYS || $PTP_CLOCK_OWNER == CHRONYD ]]; then
        for service in "${active[@]}"; do
            PTP_CONFLICTING_SERVICES="${PTP_CONFLICTING_SERVICES:+$PTP_CONFLICTING_SERVICES }$service"
        done
    else
        mapfile -t process_families < <(ptp_active_clock_process_families)
    fi
    if [[ $PTP_CLOCK_OWNER != PHC2SYS && $PTP_CLOCK_OWNER != CHRONYD ]] &&
        (( ${#active[@]} > 1 || ${#process_families[@]} > 1 )); then
        PTP_CLOCK_CONFLICTS="multiple active system time services: ${active[*]}"
        ptp_error "Multiple active system time controllers already violate the one-owner policy."
        ptp_error "Services: ${active[*]:-none}; process families: ${process_families[*]:-none}"
        return 1
    fi

    if [[ -n $PTP_CONFLICTING_SERVICES ]]; then
        PTP_CLOCK_CONFLICTS="temporary stop required: $PTP_CONFLICTING_SERVICES"
        ptp_warn "The selected architecture requires exclusive CLOCK_REALTIME ownership."
        ptp_warn "Conflicting active services: $PTP_CONFLICTING_SERVICES"
        if [[ ${PTP_SETUP_MAY_STOP_SERVICES:-0} != 1 ]]; then
            ptp_error "Run the interactive wizard to approve a temporary stop, or stop the conflict deliberately."
            return 1
        fi
    fi

    # A non-service daemon cannot be restored safely, so never kill it blindly.
    if [[ -z $PTP_CONFLICTING_SERVICES && ( $PTP_CLOCK_OWNER == PHC2SYS || $PTP_CLOCK_OWNER == CHRONYD ) ]] &&
        ptp_other_system_discipliner; then
        PTP_CLOCK_CONFLICTS="unmanaged active system-clock discipliner"
        ptp_error "A clock-disciplining process is active but is not represented by a manageable active systemd service."
        ptp_error "ptpctl will not kill an unmanaged process; stop it deliberately and retry."
        return 1
    fi
}

ptp_confirm_temporary_service_stop() {
    local answer
    [[ -n $PTP_CONFLICTING_SERVICES ]] || return 0
    if [[ ${PTPCTL_ASSUME_YES:-0} == 1 ]]; then answer=y
    else
        ptp_prompt_read "Temporarily stop $PTP_CONFLICTING_SERVICES and restore on stop/rollback? [y/N] " answer || answer=n
    fi
    case ${answer:-n} in y|Y|yes|YES|Yes) ;; *) ptp_error "Setup cancelled; conflicting service was not stopped"; return 1 ;; esac
    local service
    for service in $PTP_CONFLICTING_SERVICES; do
        ptp_service_active "$service" || continue
        systemctl stop "$service" || {
            ptp_error "Could not temporarily stop $service"
            return 1
        }
        PTP_STOPPED_SERVICES="${PTP_STOPPED_SERVICES:+$PTP_STOPPED_SERVICES }$service"
        ptp_ok "Temporarily stopped $service"
    done
    ptp_other_system_discipliner && {
        ptp_error "A competing system-clock discipliner remains active after the approved service stop"
        return 1
    }
}

ptp_restore_stopped_services() {
    local services=${1:-$PTP_STOPPED_SERVICES} service
    [[ -n $services ]] || return 0
    for service in $services; do
        if ptp_service_active "$service"; then
            ptp_info "$service is already active; no restore action needed"
        elif systemctl start "$service"; then
            ptp_ok "Restored previously active service $service"
        else
            ptp_warn "Could not restore previously active service $service; start it manually after reviewing logs"
        fi
    done
}

ptp_check_role_clock_policy() {
    local role=$1
    echo "Checking clock services..."
    ptp_clock_service_report
    if [[ ${PTPCTL_TEST_MODE:-0} == 1 && ${PTPCTL_TEST_CLOCK_CONFLICT:-0} == 1 && \
        ( $PTP_CLOCK_OWNER == PHC2SYS || $PTP_CLOCK_OWNER == CHRONYD ) ]]; then
        PTP_CLOCK_CONFLICTS="active system clock discipliner"
        ptp_error "Slave mode will use phc2sys to discipline CLOCK_REALTIME, but another discipliner is active."
        return 1
    fi
    if [[ ${PTPCTL_TEST_MODE:-0} == 1 && ${PTPCTL_TEST_CLOCK_POLICY_LIVE:-0} != 1 ]]; then
        PTP_MASTER_SOURCE_STATUS="mock-validated"
        ptp_ok "Mock clock policy accepted for dry-run testing"
        return 0
    fi
    if [[ $NTP_ENABLED == YES ]]; then
        [[ $role == master ]] && PTP_MASTER_SOURCE_STATUS=configured-NTP-pending-validation
        ptp_ok "Private chronyd will establish the configured NTP policy before dependent PTP startup"
    elif [[ $role == master ]]; then
        if ptp_system_clock_synchronized; then
            PTP_MASTER_SOURCE_STATUS=synchronized
            ptp_ok "CLOCK_REALTIME reports an upstream synchronization source"
        elif [[ $MASTER_TIME_POLICY == ALLOW_LAB_FREERUN ]]; then
            PTP_MASTER_SOURCE_STATUS=free-running-lab
            ptp_warn "LAB MASTER ONLY: CLOCK_REALTIME is not proven synchronized."
            ptp_warn "This server will act as a PTP protocol master, but its time is not traceable or guaranteed accurate."
        else
            ptp_error "CLOCK_REALTIME is not proven synchronized and MASTER_TIME_POLICY=REQUIRE_SYNCED_SYSTEM."
            ptp_error "Configure/verify chrony or another upstream source, then rerun doctor and setup."
            return 1
        fi
    elif [[ $PTP_CLOCK_OWNER == PHC2SYS ]]; then
        ptp_ok "PTP/phc2sys is the sole planned CLOCK_REALTIME controller"
    else
        ptp_ok "PTP PHC-only mode leaves CLOCK_REALTIME and its existing owner unchanged"
    fi
}

ptp_start_background() {
    local name=$1 log=$2
    shift 2
    # Runtime daemons must not inherit the setup/stop transaction lock; doing
    # so would make a successful deployment impossible to stop.
    setsid "$@" 9>&- >> "$log" 2>&1 &
    local pid=$!
    sleep 1
    if ! kill -0 "$pid" 2>/dev/null; then
        ptp_error "$name exited during startup. Recent log:"
        tail -n 40 "$log" >&2 || true
        return 1
    fi
    printf '%s\n' "$pid"
}

ptp_pmc_query() {
    local uds=$1 log=$2 command=$3 output
    output="$(pmc -u -b 0 -d "$PTP_DOMAIN" -s "$uds" "$command" 2>&1)" || {
        if [[ -w $log || ( ! -e $log && -w $(dirname "$log") ) ]]; then
            printf '%s\n' "$output" >> "$log"
        fi
        return 1
    }
    if [[ -w $log || ( ! -e $log && -w $(dirname "$log") ) ]]; then
        { echo "=== $(date --iso-8601=seconds) $command ==="; printf '%s\n' "$output"; } >> "$log"
    fi
    printf '%s\n' "$output"
}

ptp_wait_for_port_state() {
    local desired=$1 uds=$2 timeout_seconds=$3 pmc_log=$4 start now output state
    start=$(date +%s)
    while true; do
        if [[ -n ${PTP_STARTED_PTP4L_PID:-} ]] && ! kill -0 "$PTP_STARTED_PTP4L_PID" 2>/dev/null; then
            ptp_error "ptp4l exited while waiting for state $desired"
            return 1
        fi
        output="$(ptp_pmc_query "$uds" "$pmc_log" 'GET PORT_DATA_SET' 2>/dev/null || true)"
        state="$(awk '/portState/ {print $2; exit}' <<<"$output")"
        [[ $state == "$desired" ]] && { echo "$state"; return 0; }
        now=$(date +%s)
        (( now - start < timeout_seconds )) || {
            ptp_error "Timed out waiting for ptp4l state $desired (last state: ${state:-unknown})."
            return 1
        }
        sleep 2
    done
}

ptp_validate_slave_management() {
    local uds=$1 pmc_log=$2 properties status timescale offset_valid offset
    properties="$(ptp_pmc_query "$uds" "$pmc_log" 'GET TIME_PROPERTIES_DATA_SET')" || return
    timescale="$(awk '$1 == "ptpTimescale" {print $2; exit}' <<<"$properties")"
    offset_valid="$(awk '$1 == "currentUtcOffsetValid" {print $2; exit}' <<<"$properties")"
    offset="$(awk '$1 == "currentUtcOffset" {print $2; exit}' <<<"$properties")"
    [[ $timescale == 1 ]] || {
        ptp_die "Grandmaster does not advertise PTP timescale; refusing phc2sys" || return
    }
    [[ $offset_valid == 1 ]] || {
        ptp_die "Grandmaster currentUtcOffset is not valid; refusing a tens-of-seconds clock error" || return
    }
    [[ $offset =~ ^-?[0-9]+$ ]] || {
        ptp_die "Grandmaster currentUtcOffset is not numeric" || return
    }
    status="$(ptp_pmc_query "$uds" "$pmc_log" 'GET TIME_STATUS_NP' 2>/dev/null || true)"
    [[ -n $status ]] || ptp_warn "TIME_STATUS_NP was unavailable; PORT_DATA_SET and UTC properties remain valid"
}

ptp_validate_master_utc() {
    local uds=$1 pmc_log=$2 properties advertised
    properties="$(ptp_pmc_query "$uds" "$pmc_log" 'GET TIME_PROPERTIES_DATA_SET')" || return
    advertised="$(awk '/currentUtcOffset[[:space:]]/ {print $2; exit}' <<<"$properties")"
    [[ $advertised == "$MASTER_UTC_OFFSET" ]] || {
        ptp_die "ptp4l advertises currentUtcOffset=${advertised:-unknown}, expected confirmed MASTER_UTC_OFFSET=$MASTER_UTC_OFFSET" || return
    }
    ptp_ok "Master TAI-UTC offset confirmed through pmc: $advertised seconds"
}

ptp_verify_phc2sys() {
    local pid=$1 log=$2 seconds=$3
    sleep "$seconds"
    kill -0 "$pid" 2>/dev/null || {
        ptp_error "phc2sys exited. Recent log:"
        tail -n 50 "$log" >&2 || true
        return 1
    }
    grep -Eq '(^|[[:space:]])offset[[:space:]]+-?[0-9]+' "$log" || {
        ptp_error "phc2sys is running but produced no verified clock-update sample within ${seconds}s."
        tail -n 30 "$log" >&2 || true
        return 1
    }
}

ptp_stop_pid() {
    local pid=$1 expected=$2
    [[ $pid =~ ^[0-9]+$ && -d /proc/$pid ]] || return 0
    if [[ ${PTPCTL_TEST_MODE:-0} == 1 && ${PTPCTL_TEST_RUNTIME_MOCK:-0} == 1 ]]; then
        kill -TERM "$pid" 2>/dev/null || true
        return 0
    fi
    [[ $(cat "/proc/$pid/comm" 2>/dev/null || true) == "$expected" ]] || {
        ptp_warn "PID $pid is no longer $expected; not signaling it"
        return 0
    }
    kill -TERM "$pid" 2>/dev/null || true
    local i
    for i in {1..30}; do kill -0 "$pid" 2>/dev/null || return 0; sleep 0.1; done
    kill -KILL "$pid" 2>/dev/null || true
}

ptp_rollback_started() {
    ptp_warn "Setup failed; stopping only processes started by this ptpctl transaction."
    [[ -n $PTP_STARTED_PHC2SYS_PID ]] && ptp_stop_pid "$PTP_STARTED_PHC2SYS_PID" phc2sys
    [[ -n $PTP_STARTED_PTP4L_PID ]] && ptp_stop_pid "$PTP_STARTED_PTP4L_PID" ptp4l
    [[ -n $PTP_STARTED_CHRONYD_PID ]] && ptp_stop_pid "$PTP_STARTED_CHRONYD_PID" chronyd
    ptp_restore_stopped_services "$PTP_STOPPED_SERVICES"
    rm -f "$PTP_CURRENT_STATE_FILE" "$PTP_RUN_DIR/ptp4l.sock" "$PTP_RUN_DIR/ptp4l.sockro" \
        "$PTP_RUN_DIR/chronyd.sock" "$PTP_RUN_DIR/chronyd.pid"
    [[ -n $PTP_RUNTIME_CONFIG ]] && rm -f "$PTP_RUNTIME_CONFIG"
    [[ -n ${PTP_CHRONY_CONFIG:-} ]] && rm -f "$PTP_CHRONY_CONFIG"
    ptp_info "No network configuration, driver binding, service enablement, or boot setting was changed."
}

ptp_setup_signal_rollback() {
    local signal_name=$1
    if [[ $PTP_SETUP_TRANSACTION_ACTIVE == 1 ]]; then
        ptp_error "Setup interrupted by $signal_name"
        ptp_rollback_started
    fi
    exit 130
}

ptp_write_success_state() {
    local config=$1 uds=$2 ptp4l_log=$3 phc2sys_log=$4 pmc_log=$5 setup_log=$6
    local chronyd_log=${7:-} ntp_status_log=${8:-}
    ptp_atomic_write_state "$PTP_CURRENT_STATE_FILE" <<EOF
MODE=$PTP_MODE
ROLE=$PTP_ROLE
PTP_DOMAIN=$PTP_DOMAIN
TRANSPORT_SPECIFIC=$TRANSPORT_SPECIFIC
FAMILY=$PTP_FAMILY_SELECTED
INTERFACE=$PTP_IFACE
PCI=$PTP_PCI
DRIVER=$PTP_DRIVER
PHC=$PTP_PHC
PTP4L_PID=$PTP_STARTED_PTP4L_PID
PHC2SYS_PID=$PTP_STARTED_PHC2SYS_PID
CHRONYD_PID=$PTP_STARTED_CHRONYD_PID
RUNTIME_CONFIG=$config
UDS=$uds
PTP4L_LOG=$ptp4l_log
PHC2SYS_LOG=$phc2sys_log
PMC_LOG=$pmc_log
SETUP_LOG=$setup_log
CHRONY_MODE=$PTP_CHRONY_MODE
CHRONY_CONFIG=${PTP_CHRONY_CONFIG:-}
CHRONY_SOCKET=${PTP_CHRONY_SOCKET:-}
CHRONY_CMD_PORT=${PTP_CHRONY_CMD_PORT:-32322}
CHRONYD_LOG=$chronyd_log
NTP_STATUS_LOG=$ntp_status_log
NTP_ENABLED=$NTP_ENABLED
NTP_SERVERS=$NTP_SERVERS
PTP_SLAVE_SYSTEM_CLOCK=$PTP_SLAVE_SYSTEM_CLOCK
CLOCK_OWNER=$PTP_CLOCK_OWNER
PHC_OWNER=$PTP_PHC_OWNER
ARCHITECTURE=$PTP_ARCHITECTURE
STOPPED_SERVICES=$PTP_STOPPED_SERVICES
STARTED_AT=$(date --iso-8601=seconds)
MASTER_SOURCE_STATUS=${PTP_MASTER_SOURCE_STATUS:-external-grandmaster}
EOF
}
